c     @(#)concfmt.inc	5.1 06/22/94
C------------------------------------%INC CFMT
C                                     common /CFMT/
C
      integer*2 KSNO, KOSN, KSNA, KONO, KONA, KJD,  KSDY, KMON,
     .                KDAY, KYR,  KLST, KEST, KTEL, KTOS, KSTC, KMD,
     .                KIR,  KLR,  KIN,  KST,  KSP,  KVRF, KVDF, KPOC,
     .                KDIR, KSW1, KSRT, KEOP, KHR,  KVR,  KIRA, KIDC,
     .                KFOC, KORI, KZEN, KDOR, KEV,  KARA, KADC, K50R,
     .                K50D, KGL,  KGB,  KOH,  KOV,  KRHO, KTHE, KNT,
     .                KSTP, KCV,  KDV,  KVS,  KINT, KBW,  KRMS, KCF,
     .                KRF,  KCFM, KL1,  KLA,  KLB,  KAC,  KPCS, KCZV,
     .                KSS,  KRS,  JSSN, JERA, JRHO, JTHE, JNT,  JDB,
     .                jcv,  jcf,  jbeg, jend, jmb,  jme,  jfe
C
      COMMON /FORMAT/ KSNO, KOSN, KSNA, KONO, KONA, KJD,  KSDY, KMON,
     .                KDAY, KYR,  KLST, KEST, KTEL, KTOS, KSTC, KMD,
     .                KIR,  KLR,  KIN,  KST,  KSP,  KVRF, KVDF, KPOC,
     .                KDIR, KSW1, KSRT, KEOP, KHR,  KVR,  KIRA, KIDC,
     .                KFOC, KORI, KZEN, KDOR, KEV,  KARA, KADC, K50R,
     .                K50D, KGL,  KGB,  KOH,  KOV,  KRHO, KTHE, KNT,
     .                KSTP, KCV,  KDV,  KVS,  KINT, KBW,  KRMS, KCF,
     .                KRF,  KCFM, KL1,  KLA,  KLB,  KAC,  KPCS, KCZV,
     .                KSS,  KRS,  JSSN, JERA, JRHO, JTHE, JNT,  JDB,
     .                jcv,  jcf,  jbeg, jend, jmb,  jme,  jfe
C
