#!/bin/sh
# .openwin-init - OpenWindows initialization script.
# WARNING: This file is automatically generated.
#          Any changes you make here will be lost!
export DISPLAY
IFS=.
SETBASEDISPLAY() { BASEDISPLAY=$1; }
SETBASEDISPLAY ${DISPLAY}
IFS=
SETDISPLAYSCREEN() {
	DISPLAY=${BASEDISPLAY}.$1
	if winsysck x11 ; then
		:
	else
		echo No display available for screen $1
		exit 1
	fi
	eval `svenv -env`
}
# Note: toolwait is a utility to control client startup.
#       For more information, see the toolwait(1) man page.
#
# Start clients on screen 0
#
SETDISPLAYSCREEN 0
#
toolwait cmdtool -Wp 0 0 -Ws 627 161 -WP 3 833 +Wi -C 
toolwait cmdtool -Wp 523 311 -Ws 593 461 -WP 988 825 +Wi 
toolwait clock -Wp 120 120 -Ws 150 150 -WP 831 826 -Wi +Wn -alarmtime 0:0 
toolwait cmdtool -Wp 549 0 -Ws 593 461 -WP 1081 5 -Wi 
toolwait mailtool -Wp 2 185 -Ws 585 281 -WP 1068 818  -Wi  
toolwait calctool -Wp 150 150 -Ws 454 296 -WP 746 829 -Wi -2 -c -l +Wn -a 2 
toolwait helpviewer -Wp 3 192 -Ws 510 602 -WP 917 824  -Wi 'handbooks/desktop.intro.handbook.Z'
