# @(#)Makefile	5.1 06/22/94
# Recreates Unipops FONTS directory
#
FONTLIST = compro gothgr special compsc gothit triplit \
	   cyrillic greek triplro compgr duplex roman \
	   compit gothen script

all:	$(FONTLIST)

clean:
	-sccs clean
