#
#  @(#)Makefile	5.1 06/22/94
#
# Makes spectral line procedures
#
PROCS = a.prc add.prc addfeed.prc all.prc annotate.prc badch.prc beep.prc \
	bset.prc bset1.prc bset2.prc bsets.prc c1p1.prc c1p2.prc \
	cb.prc cb1.prc cb2.prc cboth.prc cbavg.prc cf1.prc cf2.prc cfetch.prc \
	charsets.prc chkavrg.prc con_c1.prc con_c2.prc con_cb.prc \
	con_prcstack.prc con_pstack.prc conver.prc cs1.prc cs2.prc cstack.prc \
	cubeinput.prc dbref.prc degcvrt.prc degtrig.prc disp12m.prc dms.prc \
	fbdata.prc fbmode.prc five.prc fivel1.prc fivel2.prc fiveline.prc \
	foca1.prc foca2.prc focalize.prc fold.prc g.prc gaussfit.prc \
	gbtipping.prc gcdisp12m.prc gdisp12m.prc getscan.prc gfbmode.prc \
	grand.prc gset.prc gshow.prc halves.prc hcdata.prc head.prc \
	integ2dim.prc ldisk.prc m1.prc m2.prc mm.prc mm1.prc mm2.prc mmath.prc \
	multislice.prc mxx.prc nrset.prc peak2dim.prc prc2dim.prc prcstack.prc \
	prcstk.prc process.prc psmsave.prc pstack.prc reset.prc seq.prc \
	sortstk.prc sptip.prc sptip1.prc sptip2.prc stip.prc t.prc testscn.prc \
	testscn2.prc tileplace.prc tileprep.prc tilesaves.prc tonns.prc \
	value_cell.prc vxgrid.prc vxmatrix.prc vygrid.prc vymatrix.prc xx.prc \
	xx12m.prc xygrid.prc xyinteg.prc xymatrix.prc xypeak.prc

PLIBS = LSETUP.12meter CSETUP.12meter maps.plib tile.plib

clean:
	-sccs clean

all: $(PROCS) $(PLIBS)

