#!/bin/csh -f
#
#   @(#)gbcondar.sh	5.2 08/02/94
#
# Determines whether to call condar or condar.rmt
#
onintr ERROR
#
setenv INFANTS /tmp/Infants.$$
if (-e $INFANTS) rm -f $INFANTS
touch $INFANTS
#
if (`hostname` == "fahd") then
   ${popsdir}sunbin/gbcondar.exe
else
   ${popsdir}sunbin/gbcondar.rmt.exe
endif
#
ERROR:
${popsdir}sunbin/infantcide $INFANTS
rm $INFANTS
