#! /bin/csh -f
# @(#)qmsprint.sh	5.1 06/22/94
# Script for printing in TEK4010 format to QMS printer
#
if ($#argv < 2) exit(1)
if (-z $2) exit(0)
#
echo "cat ${popsdir}sunbin/qmsstart $2 ${popsdir}sunbin/qmsterm | $1" | /bin/csh -f
